name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches: '*'

jobs:
  quality:
    name: Build and Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Use Node ${{ matrix.node }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}

      - name: Install deps (with cache)
        uses: bahmutov/npm-install@v1

      - name: Lint
        run: yarn lint

      - name: Format check
        run: yarn prettier:check

      - name: Typescript check
        run: yarn tsc

      - name: Test
        run: yarn test --ci --coverage --maxWorkers=2

      - name: Build
        run: yarn build

      - name: Build storybook
        run: yarn build:storybook

  publish:
    name: Publish
    if: ${{ github.ref == 'refs/heads/master' }}
    needs: [quality]
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Use Node ${{ matrix.node }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}

      - name: Install deps (with cache)
        uses: bahmutov/npm-install@v1

      - name: Build
        run: yarn build

      - name: Publish
        run: yarn semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.DESIGN_SYSTEM_RW }}

      - name: Build Storybook
        run: yarn build:storybook -o ./public

      - name: Deploy to GitHub Pages
        run: yarn deploy:storybook
        env:
          GH_TOKEN: ${{ github.actor }}:${{ secrets.DESIGN_SYSTEM_RW }}
