name: Publish

on:
  push:
    branches: [master]
  pull_request:
    branches: '*'

jobs:
  publish:
    name: Publish
    # if: ${{ github.ref == 'refs/heads/master' }}
    needs: [quality]
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Use Node ${{ matrix.node }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}

      - name: Install deps (with cache)
        uses: bahmutov/npm-install@v1

      - name: Build
        run: yarn build

      - name: Publish
        run: yarn semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Build Storybook
        run: yarn build-storybook -o ./public
